SELECT * FROM PRODUCT_INFO WHERE PRODUCT_ID = 3;
/* Test product image */
SELECT p.*, pi.IMAGE_URL FROM product AS P JOIN product_image as pi on p.PRODUCT_ID = pi.PRODUCT_ID WHERE p.PRODUCT_ID = 1;

/* Test product option*/
SELECT P.* FROM PRODUCT AS P JOIN PRODUCT_OPTION AS PO ON P.PRODUCT_ID = PO.PRODUCT_ID WHERE P.PRODUCT_ID = 1;

/* Test user */
SELECT * FROM USER WHERE user_name = "nvba";
/* Lấy sản phẩm cùng lượt đánh giá */
SELECT distinct P.*, PI.IMAGE_URL, R.RATE_NUMBER 
FROM PRODUCT AS P INNER JOIN PRODUCT_IMAGE AS PI ON P.PRODUCT_ID = PI.PRODUCT_ID 
				  INNER JOIN RATE_PRODUCT AS R ON P.PRODUCT_ID = R.PRODUCT_ID;
                  
/* Tính tổng lượt đánh giá của sản phẩm theo product id */
SELECT COUNT(*) FROM RATE_PRODUCT WHERE PRODUCT_ID = 10;
SELECT * FROM RATE_PRODUCT WHERE PRODUCT_ID = 1;

/* Tính trung bình cộng lượt đánh giá của sản phẩm theo product id */
SELECT CASE AVG(RATE_NUMBER) WHEN IFNULL(AVG(RATE_NUMBER),0) THEN 0 ELSE 1 END RATE_AVERAGE FROM RATE_PRODUCT WHERE PRODUCT_ID = 1;

/*-----------------------------*/
SELECT  AVG(RATE_NUMBER) FROM RATE_PRODUCT WHERE PRODUCT_ID = 1;
/* Tính số lượng đánh giá cho mỗi lượt*/
SELECT COUNT(RATE_NUMBER) AS RATE_TOTAL FROM RATE_PRODUCT WHERE PRODUCT_ID = 1 AND RATE_NUMBER = 5 
UNION ALL
SELECT COUNT(RATE_NUMBER) AS RATE_TOTAL FROM RATE_PRODUCT WHERE PRODUCT_ID = 1 AND RATE_NUMBER = 4
UNION ALL
SELECT COUNT(RATE_NUMBER) AS RATE_TOTAL FROM RATE_PRODUCT WHERE PRODUCT_ID = 1 AND RATE_NUMBER = 3
UNION ALL
SELECT COUNT(RATE_NUMBER) AS RATE_TOTAL FROM RATE_PRODUCT WHERE PRODUCT_ID = 1 AND RATE_NUMBER = 2
UNION ALL
SELECT COUNT(RATE_NUMBER) AS RATE_TOTAL FROM RATE_PRODUCT WHERE PRODUCT_ID = 1 AND RATE_NUMBER = 1;
/*-----------------------------*/
/* Lấy danh sách ảnh của sản phẩm theo product id */
SELECT IMAGE_URL FROM PRODUCT_IMAGE WHERE PRODUCT_ID = 17 LIMIT 1;

/* Lấy danh sách điện thoại nổi bật */
SELECT * FROM PRODUCT LIMIT 5;

/* START QUERY PRODUCT DETAIL PAGE*/
/* Lấy danh sách màu theo bộ nhớ và id của sản phẩm */
SELECT * FROM PRODUCT_OPTION WHERE MEMORY_PRODUCT = 128 AND PRODUCT_ID = 1;
/* Lấy danh bộ nhớ theo product_id */
SELECT DISTINCT MEMORY_PRODUCT FROM PRODUCT_OPTION WHERE PRODUCT_ID = 1;
/* List<String> imagesUrl Lấy danh sách đường dẫn của sản phẩm theo product_id */
SELECT IMAGE_URL FROM PRODUCT_IMAGE WHERE PRODUCT_ID = 1;
/* ProductInfo */
SELECT * FROM PRODUCT_INFO WHERE PRODUCT_ID = 1;
/* ProductOption */
SELECT * FROM PRODUCT_OPTION WHERE PRODUCT_ID = 1 LIMIT 1;
/* ProductComment */
SELECT * FROM PRODUCT_COMMENT WHERE PRODUCT_ID = 1;
/* Truy vấn để lấy ra giá hiện tại của sản phẩm */
SELECT MIN(SALE_PRICE) FROM PRODUCT_OPTION WHERE PRODUCT_ID = 1;
/* Query lấy bộ nhớ và giá của sản phẩm*/
SELECT DISTINCT MEMORY_PRODUCT, SALE_PRICE, PRODUCT_ID  FROM PRODUCT_OPTION WHERE PRODUCT_ID = 1;

SELECT   P.MEMORY_PRODUCT, P.SALE_PRICE, P.PRODUCT_ID  FROM PRODUCT_OPTION AS P  WHERE P.PRODUCT_ID = 1;
SELECT P.product_id, P.memory_product, P.sale_price  FROM PRODUCT_OPTION AS P;

/* QUERY USER TABLE*/
/* Kiểm tra thông tin đăng nhập */
SELECT * FROM USER WHERE USER_NAME = 'nva' AND PASSWORD = '123';
SELECT * FROM  USER  WHERE USERNAME = 'admin' AND PASSWORD = 'ad17b460ce87deba47d925fa26fe9520';

/*---------------------------------*/
/* QUERY PRODUCT DETAIL */
/* Truy vấn lấy danh sách bình luận theo mã sản phẩm*/
SELECT PM.COMMENT_CONTENT, PM.DATE_OF_COMMENT, U.FULL_NAME, U.AVATAR_URL, RP.RATE_NUMBER
FROM PRODUCT AS P 
		JOIN (SELECT PC.* FROM PRODUCT_COMMENT AS PC JOIN PRODUCT AS P ON PC.PRODUCT_ID = P.PRODUCT_ID WHERE PC.PRODUCT_ID = 1) AS PM ON P.PRODUCT_ID = PM.PRODUCT_ID
		JOIN USER AS U ON PM.USER_ID = U.USER_ID 
		JOIN (SELECT R.USER_ID, R.RATE_NUMBER FROM RATE_PRODUCT AS R JOIN PRODUCT AS P ON R.PRODUCT_ID = P.PRODUCT_ID WHERE R.PRODUCT_ID = 1) 
        AS RP ON RP.USER_ID = U.USER_ID;
        
SELECT PM.COMMENT_CONTENT, PM.DATE_OF_COMMENT, PM.IMAGE_COMMENT_URL, U.USER_ID, U.FULL_NAME, U.AVATAR_URL, RP.RATE_NUMBER
FROM PRODUCT AS P 
		JOIN PRODUCT_COMMENT AS PM ON P.PRODUCT_ID = PM.PRODUCT_ID
		JOIN USER AS U ON PM.USER_ID = U.USER_ID 
		JOIN RATE_PRODUCT AS RP ON RP.USER_ID = U.USER_ID
WHERE PM.PRODUCT_ID = 1 AND RP.PRODUCT_ID = 1;
/* START ADD TO CARD*/
/* Lấy productEntity theo productOptionId */
SELECT P.* FROM PRODUCT_OPTION AS PO JOIN PRODUCT AS P ON PO.PRODUCT_ID = P.PRODUCT_ID WHERE PO.PRODUCT_OPTION_ID = 1;
/* Lấy giá cho sản phẩm */
SELECT SALE_PRICE FROM PRODUCT_OPTION WHERE PRODUCT_OPTION_ID = 1;
/*---------------------------------*/
/* Lấy danh sách sản hóa đơn theo mã hóa đơn ở bảng chi tiết hóa đơn mua hàng */
SELECT * FROM PURCHASE_DETAIL WHERE PURCHASE_ID = 1;
