
select
purchaseen0_.PURCHASE_ID as purchase1_8_4_,
purchaseen0_.DATE_OF_ORDER as date_of_2_8_4_,
purchaseen0_.OPTION_SHIPPING_ID as option_s3_8_4_,
purchaseen0_.PAYMENT_METHOD_ID as payment_4_8_4_,
purchaseen0_.PURCHASE_STATUS_ID as purchase5_8_4_,
purchaseen0_.USER_ID as user_id6_8_4_,
optionship1_.OPTION_SHIPPING_ID as option_s1_1_0_,

/* START QUERY PRODUCT DETAIL PAGE*/
/* Product Option Lấy danh sách màu theo bộ nhớ và id của sản phẩm */
SELECT * FROM PRODUCT_OPTION WHERE MEMORY_PRODUCT = 128 AND PRODUCT_ID = 1;
/* Lấy danh bộ nhớ theo product_id */
SELECT DISTINCT MEMORY_PRODUCT FROM PRODUCT_OPTION WHERE PRODUCT_ID = 1;
/* List<String> imagesUrl Lấy danh sách đường dẫn của sản phẩm theo product_id */
SELECT IMAGE_URL FROM PRODUCT_IMAGE WHERE PRODUCT_ID = 1;
/* ProductInfo */
SELECT * FROM PRODUCT_INFO WHERE PRODUCT_ID = 1;
/* Product Option cho sản phẩm*/

SELECT * FROM PRODUCT_OPTION WHERE PRODUCT_ID = 1 LIMIT 1;

/* Lấy trung bình đánh giá cho mỗi đánh giá : Dùng bảng tạm */
/* Lấy tất cả đánh giá về sản phẩm*/
SELECT PM.COMMENT_CONTENT, PM.DATE_OF_COMMENT, U.FULL_NAME, U.AVATAR_URL, RP.RATE_NUMBER
FROM PRODUCT AS P 
			JOIN (SELECT PC.* FROM PRODUCT_COMMENT AS PC JOIN PRODUCT AS P ON PC.PRODUCT_ID = P.PRODUCT_ID WHERE PC.PRODUCT_ID = 1) AS PM ON P.PRODUCT_ID = PM.PRODUCT_ID 
			JOIN USER AS U ON PM.USER_ID = U.USER_ID 
            JOIN (SELECT R.* FROM RATE_PRODUCT AS R JOIN PRODUCT AS P ON R.PRODUCT_ID = P.PRODUCT_ID WHERE R.PRODUCT_ID = 1) AS RP ON RP.USER_ID = U.USER_ID 
WHERE P.PRODUCT_ID = 1;

SELECT R.* FROM RATE_PRODUCT AS R JOIN PRODUCT AS P ON R.PRODUCT_ID = P.PRODUCT_ID WHERE R.PRODUCT_ID = 1;
SELECT PC.* FROM PRODUCT_COMMENT AS PC JOIN PRODUCT AS P ON PC.PRODUCT_ID = P.PRODUCT_ID WHERE PC.PRODUCT_ID = 1;

/* Lấy ra hóa đơn vừa mới tạo */
SELECT P.* FROM PURCHASE AS P WHERE P.PURCHASE_ID = (SELECT MAX(PURCHASE_ID) FROM PURCHASE);

/* LỊCH SỬ MUA HÀNG*/
/* Lấy danh sách mua hàng theo id người dùng*/
SELECT 
	PCD.PURCHASE_DETAIL_ID, P.PRODUCT_NAME, 
    PO.COLOR_PRODUCT_NAME, PO.MEMORY_PRODUCT, PCD.SALE_PRICE, PCD.QUANTITY, PC.DATE_OF_ORDER,
    PCS.PURCHASE_STATUS_NAME, U.FULL_NAME, PO.IMAGE_URL
FROM PURCHASE_DETAIL AS PCD 
	JOIN PRODUCT AS P ON PCD.PRODUCT_ID = P.PRODUCT_ID
    JOIN PRODUCT_OPTION AS PO ON PCD.PRODUCT_OPTION_ID = PO.PRODUCT_OPTION_ID
	JOIN PURCHASE AS PC ON PCD.PURCHASE_ID = PC.PURCHASE_ID
    JOIN USER AS U ON PC.USER_ID = U.USER_ID
    JOIN PURCHASE_STATUS AS PCS ON PC.PURCHASE_STATUS_ID = PCS.PURCHASE_STATUS_ID
WHERE U.USER_ID = 2
ORDER BY PCD.PURCHASE_DETAIL_ID DESC;

/* Lấy danh sách hóa đơn */
SELECT 
	PCD.PURCHASE_DETAIL_ID, P.PRODUCT_NAME, 
    PO.COLOR_PRODUCT_NAME, PO.MEMORY_PRODUCT, PCD.SALE_PRICE, PCD.QUANTITY, PC.DATE_OF_ORDER,
    PCS.PURCHASE_STATUS_NAME, U.FULL_NAME, PO.IMAGE_URL, PC.PURCHASE_ID
FROM PURCHASE_DETAIL AS PCD 
	JOIN PRODUCT AS P ON PCD.PRODUCT_ID = P.PRODUCT_ID
    JOIN PRODUCT_OPTION AS PO ON PCD.PRODUCT_OPTION_ID = PO.PRODUCT_OPTION_ID
	JOIN PURCHASE AS PC ON PCD.PURCHASE_ID = PC.PURCHASE_ID
    JOIN USER AS U ON PC.USER_ID = U.USER_ID
    JOIN PURCHASE_STATUS AS PCS ON PC.PURCHASE_STATUS_ID = PCS.PURCHASE_STATUS_ID
ORDER BY PCD.PURCHASE_DETAIL_ID DESC;

/* Lấy hóa đơn chi tiết theo mã hóa đơn chi tiết*/
SELECT 
	PCD.PURCHASE_DETAIL_ID, P.PRODUCT_NAME, 
    PO.COLOR_PRODUCT_NAME, PO.MEMORY_PRODUCT, PCD.SALE_PRICE, PCD.QUANTITY, PC.DATE_OF_ORDER,
    PCS.PURCHASE_STATUS_NAME, U.FULL_NAME, PO.IMAGE_URL, PC.PURCHASE_ID
FROM PURCHASE_DETAIL AS PCD 
	JOIN PRODUCT AS P ON PCD.PRODUCT_ID = P.PRODUCT_ID
    JOIN PRODUCT_OPTION AS PO ON PCD.PRODUCT_OPTION_ID = PO.PRODUCT_OPTION_ID
	JOIN PURCHASE AS PC ON PCD.PURCHASE_ID = PC.PURCHASE_ID
    JOIN USER AS U ON PC.USER_ID = U.USER_ID
    JOIN PURCHASE_STATUS AS PCS ON PC.PURCHASE_STATUS_ID = PCS.PURCHASE_STATUS_ID
WHERE PCD.PURCHASE_DETAIL_ID = 1;
/*----------------------------*/
/* RATE PRODUCT */
/* Tính tổng số đánh giá trên mỗi sản phẩm*/
SELECT COUNT(RATE_NUMBER) FROM PRODUCT_COMMENT WHERE PRODUCT_ID = 1;

/* Tính đánh giá trung bình cho từng sản phẩm*/
SELECT AVG(RATE_NUMBER) FROM PRODUCT_COMMENT WHERE PRODUCT_ID = 1;

/* Tính số lượng đánh giá cho mỗi lượt*/
SELECT COUNT(RATE_NUMBER) AS RATE_TOTAL FROM PRODUCT_COMMENT WHERE PRODUCT_ID = 1 AND RATE_NUMBER = 5 
UNION ALL
SELECT COUNT(RATE_NUMBER) AS RATE_TOTAL FROM PRODUCT_COMMENT WHERE PRODUCT_ID = 1 AND RATE_NUMBER = 4
UNION ALL
SELECT COUNT(RATE_NUMBER) AS RATE_TOTAL FROM PRODUCT_COMMENT WHERE PRODUCT_ID = 1 AND RATE_NUMBER = 3
UNION ALL
SELECT COUNT(RATE_NUMBER) AS RATE_TOTAL FROM PRODUCT_COMMENT WHERE PRODUCT_ID = 1 AND RATE_NUMBER = 2
UNION ALL
SELECT COUNT(RATE_NUMBER) AS RATE_TOTAL FROM PRODUCT_COMMENT WHERE PRODUCT_ID = 1 AND RATE_NUMBER = 1;
/*-----------------------------*/
/* Lấy danh sách ảnh của sản phẩm theo product id */
SELECT IMAGE_URL FROM PRODUCT_IMAGE WHERE PRODUCT_ID = 17 LIMIT 1;

/* Lấy danh sách điện thoại nổi bật */
SELECT * FROM PRODUCT LIMIT 5;

/* START QUERY PRODUCT DETAIL PAGE*/
/* Lấy danh sách màu theo bộ nhớ và id của sản phẩm */
SELECT * FROM PRODUCT_OPTION WHERE MEMORY_PRODUCT = 128 AND PRODUCT_ID = 1;
/* Lấy danh bộ nhớ theo product_id */
SELECT DISTINCT MEMORY_PRODUCT FROM PRODUCT_OPTION WHERE PRODUCT_ID = 1;
/* List<String> imagesUrl Lấy danh sách đường dẫn của sản phẩm theo product_id */
SELECT IMAGE_URL FROM PRODUCT_IMAGE WHERE PRODUCT_ID = 1;
/* ProductInfo */
SELECT * FROM PRODUCT_INFO WHERE PRODUCT_ID = 1;
/* ProductOption */
SELECT * FROM PRODUCT_OPTION WHERE PRODUCT_ID = 1 LIMIT 1;
/* ProductComment */
SELECT * FROM PRODUCT_COMMENT WHERE PRODUCT_ID = 1;
/* Truy vấn để lấy ra giá hiện tại của sản phẩm */
SELECT MIN(SALE_PRICE) FROM PRODUCT_OPTION WHERE PRODUCT_ID = 1;
/* Query lấy bộ nhớ và giá của sản phẩm*/
SELECT DISTINCT MEMORY_PRODUCT, SALE_PRICE, PRODUCT_ID  FROM PRODUCT_OPTION WHERE PRODUCT_ID = 1;

SELECT   P.MEMORY_PRODUCT, P.SALE_PRICE, P.PRODUCT_ID  FROM PRODUCT_OPTION AS P  WHERE P.PRODUCT_ID = 1;
SELECT P.product_id, P.memory_product, P.sale_price  FROM PRODUCT_OPTION AS P;

/* QUERY USER TABLE*/
/* Kiểm tra thông tin đăng nhập */
SELECT * FROM USER WHERE USER_NAME = 'nva' AND PASSWORD = '123';
SELECT * FROM  USER  WHERE USERNAME = 'admin' AND PASSWORD = 'ad17b460ce87deba47d925fa26fe9520';

/*---------------------------------*/
/* QUERY PRODUCT DETAIL */
/* Truy vấn lấy danh sách bình luận theo mã sản phẩm*/
SELECT PC.PRODUCT_ID, PC.COMMENT_CONTENT, PC.DATE_OF_COMMENT, PC.IMAGE_COMMENT_URL, PC.RATE_NUMBER, U.FULL_NAME, U.AVATAR_URL
FROM PRODUCT_COMMENT AS PC JOIN USER AS U ON PC.USER_ID = U.USER_ID
WHERE PC.PRODUCT_ID = 1
ORDER BY PC.PRODUCT_COMMENT_ID DESC LIMIT 3;

/* START ADD TO CARD*/
/* Lấy productEntity theo productOptionId */
SELECT P.* FROM PRODUCT_OPTION AS PO JOIN PRODUCT AS P ON PO.PRODUCT_ID = P.PRODUCT_ID WHERE PO.PRODUCT_OPTION_ID = 1;
/* Lấy giá cho sản phẩm */
SELECT SALE_PRICE FROM PRODUCT_OPTION WHERE PRODUCT_OPTION_ID = 1;

/*---------------------------------*/
/* Lấy danh sách sản hóa đơn theo mã hóa đơn ở bảng chi tiết hóa đơn mua hàng */
SELECT * FROM PURCHASE_DETAIL WHERE PURCHASE_ID = 1;
